version: '3'

services:
  rag-chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./vector_stores:/app/vector_stores
      - ./chat_history:/app/chat_history
    env_file:
      - .env
